"""message

Revision ID: 02c8ec92f9eb
Revises: 793bc4490f30
Create Date: 2023-10-04 05:56:34.859476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c8ec92f9eb'
down_revision = '793bc4490f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strAlcoholic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('strAlcoholic')

    # ### end Alembic commands ###
