"""message

Revision ID: fc8229f7935c
Revises: 6d42d4e8c107
Create Date: 2023-10-06 19:25:31.150320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8229f7935c'
down_revision = '6d42d4e8c107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_list', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
